name: Publish Package

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean npm install
        run: |
          npm ci
          npm cache clean --force

      - name: Compile TypeScript code
        run: npx tsc

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
